if (SPARSKIT_LIBRARIES)
  set(SPARSKIT_FIND_QUIETLY TRUE)
endif (SPARSKIT_LIBRARIES)

find_library(SPARSKIT_LIBRARY skit PATHS $ENV{SPARSKITDIR}/lib ${SPARSKITDIR}/lib $ENV{SPARSKITDIR} ${SPARSKITDIR} ${LIB_INSTALL_DIR})
set(SPARSKIT_LIBRARIES ${SPARSKIT_LIBRARY})

find_package(BLAS)
if (SPARSKIT_LIBRARY AND BLAS_FOUND AND Fortran_FOUND)
    set(SPARSKIT_LIBRARIES ${SPARSKIT_LIBRARIES} ${SPARSKIT_LIBRARY} ${BLAS_LIBRARIES} ${CMAKE_Fortran_IMPLICIT_LINK_LIBRARIES})
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SPARSKIT DEFAULT_MSG SPARSKIT_LIBRARY SPARSKIT_LIBRARIES)

mark_as_advanced(SPARSKIT_INCLUDE SPARSKIT_LIBRARY SPARSKIT_LIBRARIES)

